# list of paths to necessary scripts.json
:dependency_paths:
  - '../core/Source'  # Mootools Core
  - '../more/Source'  # Mootools More
  - './Source'                 # This project

# output file path
:build_path: './built.js'
