copyright: Unknown
description: Unknown
name: clientcide
sources: [Source/Core/dbug.js, Source/Core/Clientcide.js, Source/3rdParty/Autocompleter.Remote.js,
  Source/3rdParty/Lightbox.js, Source/3rdParty/Autocompleter.js, Source/3rdParty/Autocompleter.Observer.js,
  Source/3rdParty/Autocompleter.Clientcide.js, Source/3rdParty/Autocompleter.JSONP.js,
  Source/3rdParty/Autocompleter.Local.js, Source/Layout/MenuSlider.js, Source/Layout/MooScroller.js,
  Source/Layout/Collapsible.js, Source/Layout/SimpleCarousel.js, Source/Layout/MultipleOpenAccordion.js,
  Source/Layout/SimpleSlideShow.js, Source/Layout/HoverGroup.js, Source/Layout/TabSwapper.js,
  Source/Compatability/Browser.Extras.Compat.js, Source/Compatability/OverText.Compat.js,
  Source/Compatability/DollarE.Compat.js, Source/Compatability/Modalizer.Compat.js,
  Source/Compatability/String.Extras.Compat.js, Source/Compatability/Request.Queue.Compat.js,
  Source/Compatability/Class.Refactor.Compat.js, Source/Compatability/DollarG.Compat.js,
  Source/Compatability/Waiter.Compat.js, Source/Compatability/Element.Shortcuts.Compat.js,
  Source/Compatability/JsonP.Compat.js, Source/Compatability/IframeShim.Compat.js,
  Source/Compatability/Element.Forms.Compat.js, Source/Compatability/Date.Compat.js,
  Source/Compatability/Element.Position.Compat.js, Source/Compatability/Element.MouseOvers.Compat.js,
  Source/Localization/SimpleEditor.Spanish.js, Source/Localization/SimpleEditor.Portuguese.js,
  Source/Localization/SimpleEditor.Italian.js, Source/Localization/SimpleEditor.French.js,
  Source/Localization/SimpleEditor.English.US.js, Source/Localization/SimpleEditor.Dutch.js,
  Source/Fx/Fx.Marquee.js, Source/Forms/DatePicker.js, Source/Forms/TagMaker.js, Source/Forms/Form.Validator.Tips.js,
  Source/Forms/ProductPicker.js, Source/Forms/DatePicker.Extras.js, Source/Forms/Confirmer.js,
  Source/Forms/Form.Request.Prompt.js, Source/Forms/InputFocus.js, Source/Forms/SimpleEditor.js,
  Source/Beta/PostEditor.Forum.js, Source/Beta/PostEditor.js, Source/UI/StickyWin.js,
  Source/UI/StickyWin.Ajax.js, Source/UI/StickyWin.Modal.js, Source/UI/IconMenu.js,
  Source/UI/StickyWin.Prompt.js, Source/UI/StickyWin.Confirm.js, Source/UI/StickyWin.Alert.js,
  Source/UI/Tips.Pointy.js, Source/UI/StickyWin.Drag.js, Source/UI/ObjectBrowser.js,
  Source/UI/StyleWriter.js, Source/UI/StickyWin.UI.Pointy.js, Source/UI/StickyWin.PointyTip.js,
  Source/UI/StickyWin.UI.js, Source/UI/PopupDetails.js, Source/UI/StickyWin.Fx.js,
  Source/Class/Class.ToElement.js, Source/Browser/Popup.js, Source/Browser/FixPNG.js]
version: 2.2.0